### ISSUE TITLE
Akun Github

### ISSUE THREAD

**Issue by sevinurafni** [sevinurafni/ST110123#1]

**Comment by HansDarmawanS** [comment]
https://github.com/HansDarmawanS

**Comment by rafaza24** [comment]
https://github.com/rafaza24

**Comment by revaanwarr** [comment]
https://github.com/revaanwarr

**Comment by nadinevaliaa** [comment]
https://github.com/nadinevaliaa

**Comment by Budikurnia26** [comment]
https://github.com/Budikurnia26

**Comment by AmeliaReginaa** [comment]
https://github.com/AmeliaReginaa

**Comment by IBRAHIM354313** [comment]
https://github.com/IBRAHIM354313

**Comment by najliaa** [comment]
https://github.com/najliaa

**Comment by ArielaSafra** [comment]
https://github.com/ArielaSafra

**Comment by ryynnptr** [comment]
https://github.com/ryynnptr

**Comment by fadhlijahfal1** [comment]
https://github.com/fadhlijahfal1

**Comment by ajisakti554** [comment]
https://github.com/ajisakti554

**Comment by yusufsf01** [comment]
https://github.com/yusufsf01

**Comment by Rizwar11** [comment]
https://github.com/Rizwersaepuloh11

**Comment by Rizwar11** [comment]
https://github.com/Rizwar11

**Comment by ApikMu** [comment]
https://github.com/ApikMu

**Comment by KanayaDzikra** [comment]
https://github.com/KanayaDzikra

**Comment by FitriFatimah6** [comment]
https://github.com/FitriFatimah6

**Comment by IBRAHIM354313** [comment]
[TUGAS ALPO MUSA 2C2230002.pdf](https://github.com/sevinurafni/ST110123/files/13777947/TUGAS.ALPO.MUSA.2C2230002.pdf)
assalamualaikum kak,ini tugas saya 
Nama : Muhammad Musa Ibrahim
Nrp : 2C2230002
Program Studi : Science Data 
maaf kak mengganggu waktu liburannya
