### ISSUE TITLE
Tugas 2 Agribisnis

### ISSUE THREAD

**Issue by sevinurafni** [sevinurafni/ST110123#10]
Nama - NRP
Link repository tugas

contoh:
Sevi - 201520001
https://github.com/sevinurafni/ST110123

Deadline 23 Januari 2024 pukul 23:59.

Tugas:
1. Jelaskan alur program dan buatkan flowchart dari program konversi nilai yang ada di modul [https://github.com/sevinurafni/ST110123/blob/main/PemilihanKondisi.md](url)
2. Buatkan program dengan menggunakan for, while, dan do-while agar menampilkan:
(sertakan caprure hasil running program)
> iterasi ke-10
iterasi ke-9
iterasi ke-8
iterasi ke-7
iterasi ke-6
iterasi ke-5

**Comment by alyanrni25** [comment]
Alya Nuraeni - 2C1230011

https://github.com/alyanrni25/TugasAlpro/tree/main/Tugas%202

**Comment by annisayustiani** [comment]
Annisa Yustiani - 2C1230007

[Tugas 2 Flowchart Konversi Nilai Annisa.pdf](https://github.com/sevinurafni/ST110123/files/13973823/Tugas.2.Flowchart.Konversi.Nilai.Annisa.pdf)

https://github.com/annisayustiani/Tugas-Alpro/tree/main/Tugas%202

**Comment by kayla0204** [comment]
Kayla Ayu - 2C1230008
[Tugas2(konversi nilai).drawio.pdf](https://github.com/sevinurafni/ST110123/files/13973835/Tugas2.konversi.nilai.drawio.pdf)
https://github.com/kayla0204/TugasAlpro/tree/main/Tugas%202

**Comment by mchydhamlna** [comment]
Moch Yudha Maulana - 2C1230001
https://github.com/nalesyn/TugasAlpro/tree/main/Tugas%202
https://github.com/nalesyn/TugasAlpro/blob/main/Tugas%202/KonversiNilai.pdf

**Comment by euisjulianingsih** [comment]
Euis julia ningsih - 2C1230006
[Uploading Tugas2(konversi nilai).pdf…]()
https://github.com/euisjulianingsih/TugasAlpro/tree/main/Tugas%202

**Comment by fenitasari** [comment]
Fenita Sari - 2C1230002
[Uploading Tugas 2 (Flowchart konversi nilai) fenitasari_2C1230002.pdf…]()
https://github.com/fenitasari/TugasAlpro/tree/main/Tugas%202

**Comment by DianaFriskaAulia** [comment]
Diana friska Aulia -2C1230004
[Tugas 2 Flowchart Konversi Nilai Diana.pdf](https://github.com/sevinurafni/ST110123/files/13973888/Tugas.2.Flowchart.Konversi.Nilai.Diana.pdf)
https://github.com/DianaFriskaAulia/TugasAlpro/tree/main/tugas%202

**Comment by RepaNurulAida** [comment]
Repa nurul aida- 2C1230009
[tugas2(konversi nilai).pdf](https://github.com/sevinurafni/ST110123/files/13973907/tugas2.konversi.nilai.pdf)
https://github.com/RepaNurulAida/TugasAlpro/tree/main/TUGAS%202

**Comment by fanitaanggraeni** [comment]
Fanita Anggraeni - 2C1230003

[tugas 2( flowchart konversi nilai )fanitaanggraeni_2c1230003.pdf](https://github.com/sevinurafni/ST110123/files/13973954/tugas.2.flowchart.konversi.nilai.fanitaanggraeni_2c1230003.pdf)
https://github.com/fanitaanggraeni/fanita-anggraeni/tree/main/fanita%20tugas%20no%202%20bikin%20pengulangan%20for%2Cwhile%2Cdo-while

**Comment by wiliagung22** [comment]
wili agung saputra - 2C1230013

[Tugas 2 Flowchart Konversi Nilai Wili.pdf](https://github.com/sevinurafni/ST110123/files/13974054/Tugas.2.Flowchart.Konversi.Nilai.Wili.pdf)

https://github.com/wiliagung22/TugasAlpro/tree/main/Tugas%202

**Comment by muhamadhilmi06** [comment]
Muhamad hilmi - 2C1230005
https://github.com/muhamadhilmi06/TugasAlpro/tree/main/Tugas%202

**Comment by fanitaanggraeni** [comment]
fanita anggraeni - 2C1230003

For
![image](https://github.com/sevinurafni/ST110123/assets/156992694/afdf8644-c39c-4f94-9558-4d83ce911541)

while
![image](https://github.com/sevinurafni/ST110123/assets/156992694/5e0d9d5c-b407-43ee-ba4f-0e60af34ecf7)
do_while
![image](https://github.com/sevinurafni/ST110123/assets/156992694/2fde7b02-d0a8-4835-a10f-fd5b6499bdc7)

file cpp:
(https://github.com/sevinurafni/ST110123/files/13974490/Fanita.Anggraeni_2C1230003_Agribisnis.zip)
