### ISSUE TITLE
Tugas 4

### ISSUE THREAD

**Issue by sainsdataikopin** [sevinurafni/ST110123#6]
Tugas 4:

1. Buat program perkalian matriks yang mana elemennya sama dengan yang ada di program penjumlahan matriks.
2. Mengubah nilai elemen array.
> ilustrasi
> nilai[3] = {85, 70, 75}
ubah index ke-0 menjadi 20
nilai[3] = {20, 70, 75}
3. Jelaskan alur program menghitung rata-rata nilai dan program penjumlahan matriks.

Deadline: Rabu, 24 Januari 2024; 23:59
Sertakan capture dari output program.

Nama - NRP
Link repository

**Comment by KanayaDzikra** [comment]
Kanaya Dzikra Setiadi - 2C2230015
https://github.com/KanayaDzikra/Alpro/blob/main/Alpro4.cpp
https://github.com/KanayaDzikra/Alpro/blob/main/alpro4.JPG
https://github.com/KanayaDzikra/Alpro/blob/main/array.cpp
https://github.com/KanayaDzikra/Alpro/blob/main/array.JPG
https://github.com/KanayaDzikra/Alpro/blob/main/Alpro4.pdf

**Comment by revaanwarr** [comment]
Reva Anwar - 2C230003
https://github.com/revaanwarr/TugasAlpro/blob/main/alpro4.cpp
https://github.com/revaanwarr/TugasAlpro/blob/main/alpro4.jpg.png
https://github.com/revaanwarr/TugasAlpro/blob/main/array.cpp
https://github.com/revaanwarr/TugasAlpro/blob/main/array.png
https://github.com/revaanwarr/TugasAlpro/blob/main/Alur%20Program

**Comment by HansDarmawanS** [comment]
Nama : Farhan Darmawan S
NRP : 2C2230017

https://github.com/HansDarmawanS/TugasAlpro

**Comment by fadhlijahfal1** [comment]
Nama : Fadhli Jahfal Aufa Maulana
NRP : 2C2230008

Link : https://github.com/fadhlijahfal1/Tugas-Algoritma-Pemrograman/tree/main/Tugas%204%20Alpro

**Comment by ryynnptr** [comment]
Nama : Riyan putra pratama
NRP : 2C2230016

https://github.com/ryynnptr/tugasalpro/tree/main/Tugas%204

**Comment by nadinevaliaa** [comment]
Nadine Valia Azzahra - 2C2230007

https://github.com/nadinevaliaa/TugasAlpro
https://github.com/nadinevaliaa/TugasAlpro/blob/main/Alur%20program.pdf
https://github.com/nadinevaliaa/TugasAlpro/blob/main/Tugas4No1.cpp
https://github.com/nadinevaliaa/TugasAlpro/blob/main/output%20tugas%204%20no%201.png
https://github.com/nadinevaliaa/TugasAlpro/blob/main/Tugas4No2.cpp
https://github.com/nadinevaliaa/TugasAlpro/blob/main/output%20tugas%204%20no%202.png

**Comment by IBRAHIM354313** [comment]
Nama : Muhammad Musa Ibrahim
Nrp.    : 2C2230002
Tugas : 4


https://github.com/IBRAHIM354313/TugasAlpro
https://github.com/IBRAHIM354313/TugasAlpro/blob/main/TugasAlpro4_soal1.cxx
https://github.com/IBRAHIM354313/TugasAlpro/blob/main/TugasAlpro4_soal2.cxx
https://github.com/IBRAHIM354313/TugasAlpro/blob/main/TugasAlpro4_Soal3.txt
https://github.com/IBRAHIM354313/TugasAlpro/blob/main/output_Tugas4_soal1_soal2.jpg

**Comment by ajisakti554** [comment]
NAMA : Aji Sakti Saputra 
NRP : 2C2230012
https://github.com/ajisakti554/Tugas-Alpro/blob/369717b252b5fd464da8f2909441bb99b1e2508a/matrikstugas1.cpp
https://github.com/ajisakti554/Tugas-Alpro/blob/369717b252b5fd464da8f2909441bb99b1e2508a/no%201.png
https://github.com/ajisakti554/Tugas-Alpro/blob/369717b252b5fd464da8f2909441bb99b1e2508a/matrikstugas2.cpp
https://github.com/ajisakti554/Tugas-Alpro/blob/369717b252b5fd464da8f2909441bb99b1e2508a/no%202.png
https://github.com/ajisakti554/Tugas-Alpro/blob/369717b252b5fd464da8f2909441bb99b1e2508a/matrikstgas3.txt

**Comment by ArielaSafra** [comment]
**Ariela Safmi Ramdhani - 2C2230005**

https://github.com/ArielaSafra/TugasAlpro/blob/main/Tugas%20Alpro-4%20(soal%201).cpp
https://github.com/ArielaSafra/TugasAlpro/blob/main/CO%5ETugas%20Alpro%204%20(1).png
https://github.com/ArielaSafra/TugasAlpro/blob/main/Tugas%20Alpro-4%20(soal%202).cpp
https://github.com/ArielaSafra/TugasAlpro/blob/main/CO%5ETugas%20Alpro-4%20(2).png
https://github.com/ArielaSafra/TugasAlpro/blob/main/Tugas%20Alpro-4%20(soal3)

**Comment by najliaa** [comment]
Najlia Intani - 2C2230010
https://github.com/najliaa/TugasAlpro/tree/main/Tugas%204

**Comment by AmeliaReginaa** [comment]
Amelia Regina Permana - 2C2230019
https://github.com/AmeliaReginaa/TugasAlpro/blob/main/Program%20Penjumlahan%20Matriks.docx
https://github.com/AmeliaReginaa/TugasAlpro/blob/main/Screenshot%202024-01-24%20193934.png
https://github.com/AmeliaReginaa/TugasAlpro/blob/main/Screenshot%202024-01-24%20193934.png
https://github.com/AmeliaReginaa/TugasAlpro/blob/main/Tugas4_Ilustrasiiiiiiiiiii.cpp
https://github.com/AmeliaReginaa/TugasAlpro/blob/main/perkalian_Matriks.cpp

**Comment by FitriFatimah6** [comment]
Fitri Fatimah-2C2230004

https://github.com/FitriFatimah6/ST110123/blob/main/TugasAlpro4perkalian.cpp

https://github.com/FitriFatimah6/ST110123/blob/main/TugasAlprono2.cpp

https://github.com/FitriFatimah6/ST110123/blob/main/Screenshot%20(26).png

https://github.com/FitriFatimah6/ST110123/blob/main/Screenshot%20(24).png

https://github.com/FitriFatimah6/ST110123/blob/main/Menghitung%20rata.pdf

https://github.com/FitriFatimah6/ST110123

**Comment by Rizwar11** [comment]
Nama: Rizwar Syaefulloh
Nrp: 2C2230009
https://github.com/Rizwar11/TugasAlpro/tree/main/Tugas%204

**Comment by yusufsf01** [comment]
Nama : Yusuf Sohibul Falah
NRP : 2C2230013
https://github.com/yusufsf01/TugasAlpro
