### ISSUE TITLE
Akun github Agribisnis

### ISSUE THREAD

**Issue by sainsdataikopin** [sevinurafni/ST110123#7]
Nama - NRP
link akun github.

contoh:
Sevi - 201520001
https://github.com/sevinurafni

**Comment by kayla0204** [comment]
Kayla ayu - 2C1230008
https://github.com/kayla0204

**Comment by fenitasari** [comment]
Fenita Sari - 2C1230002
https://github.com/fenitasari

**Comment by alyanrni25** [comment]
Alya Nuraeni - 2C1230011
https://github.com/alyanrni25

**Comment by sevinurafni** [comment]
> Nama - NRP link akun github.
> 
> contoh: Sevi - 201520001 https://github.com/sevinurafni

**Tutorial upload atau push ke repository
https://docs.github.com/en/repositories/working-with-files/managing-files/adding-a-file-to-a-repository**

**Comment by nalesyn** [comment]
Moch Yudha Maulana - 2C1230001
https://github.com/mchydhamlna

**Comment by annisayustiani** [comment]
Annisa Yustiani - 2C1230007
https://github.com/annisayustiani

**Comment by maudiiiy** [comment]
Maudina Rachmawati - 2C1230010
https://github.com/maudiiiy

**Comment by euisjulianingsih** [comment]
Euis Julia Ningsih - 2C1230006

https://github.com/euisjulianingsih

**Comment by wiliagung22** [comment]
wili agung saputra - 2C1230013
https://github.com/wiliagung22

**Comment by DianaFriskaAulia** [comment]
Diana Friska Aulia - 2C1230004
https://github.com/DianaFriskaAulia

**Comment by RepaNurulAida** [comment]
Repa Nurul Aida - 2C1230009
https://github.com/RepaNurulAida

**Comment by fanitaanggraeni** [comment]
Fanita anggraeni - 2C1230003

https://github.com/fanitaanggraeni/fanita-anggraeni
