### ISSUE TITLE
Tugas 1 Agribisnis

### ISSUE THREAD

**Issue by sainsdataikopin** [sevinurafni/ST110123#8]
Nama - NRP
Link repository tugas

contoh:
Sevi - 201520001
https://github.com/sevinurafni/ST110123

**Deadline 23 Januari 2024 pukul 23:59**.

**Comment by wiliagung22** [comment]
wili agung saputra-2C1230013

https://github.com/wiliagung22/TugasAlpro

**Comment by nalesyn** [comment]
Moch Yudha Maulana - 2C1230001
https://github.com/nalesyn/TugasAlpro

**Comment by sevinurafni** [comment]
> Nama - NRP Link repository tugas
> 
> contoh: Sevi - 201520001 https://github.com/sevinurafni/ST110123
> 
> **Deadline 23 Januari 2024 pukul 23:59**.

Sevi - 201520001 
[introduction.md](https://github.com/sevinurafni/ST110123/files/13973458/introduction.md)

**Comment by nalesyn** [comment]
Moch Yudha Maulana - 2C1230001
[](https://github.com/nalesyn/TugasAlpro/blob/main/Tugas%201/tugas2.md)

**Comment by mchydhamlna** [comment]
Moch Yudha Maulana - 2C1230001
https://github.com/mchydhamlna/TugasAlpro/blob/main/Tugas%201/tugas1.md

**Comment by kayla0204** [comment]
Kayla Ayu - 2C1230008
https://github.com/kayla0204/TugasAlpro/tree/main/Tugas1Alpro

**Comment by annisayustiani** [comment]
Annisa Yustiani - 2C1230007
https://github.com/annisayustiani/Tugas-Alpro/tree/main/Tugas1Alpro

**Comment by maudiiiy** [comment]
Maudina rachmawati - 2C1230010
https://github.com/maudiiiy/TugasAlpro/tree/main/Tugas1Alpro

**Comment by fenitasari** [comment]
Fenita Sari - 2C1230002
https://github.com/fenitasari/TugasAlpro/tree/main/Tugas1Alpro

**Comment by fanitaanggraeni** [comment]
Fanita Anggraeni-2C1230003
https://github.com/fanitaanggraeni/fanita/tree/main/Tugas1Alpro

**Comment by wiliagung22** [comment]
Wili Agung Saputra - 2C1230013
https://github.com/wiliagung22/TugasAlpro/tree/main/Tugas1Alpro

**Comment by DianaFriskaAulia** [comment]
Diana Friska Aulia - 2C1230004
https://github.com/DianaFriskaAulia/TugasAlpro/tree/main/Tugas1Alpro
